table calendario
	lineageTag: a9eec310-6292-4707-a5ce-0e85b21273e9
	dataCategory: Time

	measure 'Cotação do dia' = ```
			AVERAGE(cotacoes[Cotacao]) 
			```
		displayFolder: Medidas
		lineageTag: 951f2935-39d1-4b57-b186-985e9d3df602

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		displayFolder: Medidas
		lineageTag: cf287ed5-3576-4a3f-bf52-8dddd877fe31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		isKey
		formatString: dd/mm/yy
		displayFolder: Colunas
		lineageTag: cf7e2942-db7a-4749-96ed-e98131f4fbc8
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Ano
		dataType: int64
		formatString: 0
		displayFolder: Colunas
		lineageTag: 9f8a11c6-3f3e-46aa-9e43-1a97db7fba98
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = User

	column MesAno
		dataType: string
		displayFolder: Colunas
		lineageTag: e9fd76ac-a63d-4059-bf5b-c42abcfa02e1
		summarizeBy: none
		sourceColumn: MesAno
		sortByColumn: MesInicio

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MesInicio
		dataType: dateTime
		formatString: Long Date
		displayFolder: Colunas
		lineageTag: 0706b712-e8a6-4aa4-9a0a-4260b9a56e0e
		summarizeBy: none
		sourceColumn: MesInicio

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition calendario = m
		mode: import
		queryGroup: Dimensões
		source = ```
				let
				    dataInicial = data_inicial, 
				    dataFinal = data_final, 
				    
				    datas = List.Dates(
				        dataInicial, 
				        Duration.Days(dataFinal-dataInicial) + 1, 
				        #duration(1, 0, 0, 0)
				    ),
				
				    calendario = #table(
				        type table[
				            Data = date,
				            Ano = Int64.Type,
				            MesAno = text,
				            MesInicio = date
				        ],
				        List.Transform(
				            datas,
				            each {
				                _,
				                Date.Year(_),
				                Date.ToText(_, [Format="MMM/yy", Culture="pt-BR"]),
				                Date.StartOfMonth(_)
				            }
				        )
				    )
				
				in
				    calendario
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

